# Generated by Django 4.0.4 on 2022-06-03 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
